### ISSUE TITLE
Better responsiveness for Mobile Devices

### ISSUE THREAD

**Issue by sarthakpranesh** [aryanshridhar/Portfolio#1]
Some of the following issues related to the responsiveness of the portfolio website need to be corrected
- The heading of the different pages overflow the width of the device ( device: Galaxy S9 )
- The height of each section is a bit too much on mobile devices ( viewed on the device: Galaxy S9 )
 - The main content ( or the body of each section) has too much padding from the sides

Overall the site is amazing but needs minor fixes to the responsiveness.
Also, Try using background-color as "transparent" for the navbar.

Some helpful resources
https://www.w3schools.com/css/css_rwd_mediaqueries.asp
https://getbootstrap.com/
https://wpcrib.com/test-your-responsive-web-design/

*Best way to check the responsiveness is to use the inbuild inspect tool of the browsers

**Comment by aryanshridhar** [comment]
Thanks @sarthakpranesh  for opening this issue .
Some commits have been made to the code keeping the issues listed in mind which do enhances the responsiveness of website for mobile devices . <br>
Thank You :)
